import Head from 'next/head'
import styled from 'styled-components'

const WrapperStyles = styled.div`
  color: ${({ theme }) => theme.colors.primary};
  font-family: 'IM FELL Great Primer';
  font-style: italic;
`

const Home = () => {
  return (
    <WrapperStyles>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <p>glazurmat</p>
      </main>
    </WrapperStyles>
  )
}

export default Home
